services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/todo_app
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./.env:/app/.env
    depends_on:
      - mongo
    command: npm run dev
    
  mongo:
    image: mongo:5.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: